### ISSUE TITLE
Implement Main Form Interface

### ISSUE THREAD

**Issue by DCay** [antoniaat/Quiz-MDI-Application#1]
Implement the Main Form Interface, that the user meets upon starting the application.
* It should have a simple title "Quiz Platform" for example
* It should have a Login form or a button that opens another Form with a Login on it.
* It should have a Register from or a button that opens another Form with a Register on it.

**Comment by antoniaat** [comment]
Implemented with https://github.com/antoniaat/Quiz-MDI-Application/commit/c300784640ff54f860d67c4064006c9c6c375c7c
